[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:php-fpm]
command=docker-php-entrypoint php-fpm
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:product_scanned_consumer]
command=php /var/www/html/api-vmar/bin/console rabbitmq:consume SubtractQuantityOnProductScanned
directory=/var/www/html/api-vmar
autostart=true
autorestart=true
startsecs=5
startretries=10
stdout_logfile=/var/log/supervisor/product_scanned.log
stderr_logfile=/var/log/supervisor/product_scanned_error.log

[program:sale_finished_consumer]
command=php /var/www/html/api-vmar/bin/console rabbitmq:consume SubtractStockOnSaleFinished
directory=/var/www/html/api-vmar
autostart=true
autorestart=true
startsecs=5
startretries=10
stdout_logfile=/var/log/supervisor/sale_finished.log
stderr_logfile=/var/log/supervisor/sale_finished_error.log

[program:low_stock_consumer]
command=php /var/www/html/api-vmar/bin/console rabbitmq:consume NotifyRestockersOnLowStock
directory=/var/www/html/api-vmar
autostart=true
autorestart=true
startsecs=5
startretries=10
stdout_logfile=/var/log/supervisor/low_stock.log
stderr_logfile=/var/log/supervisor/low_stock_error.log