product_allocation_put:
  path: /product_allocation/{idSpace}
  controller: SuperVMar\App\Controller\ProductAllocation\ProductAllocationPutController
  defaults: { auth: false }
  methods: PUT

product_allocation_delete:
  path: /product_allocation/{idSpace}
  controller: SuperVMar\App\Controller\ProductAllocation\ProductAllocationDeleteController
  defaults: { auth: false }
  methods: DELETE

products_allocations_get:
  path: /products_allocations
  controller: SuperVMar\App\Controller\ProductAllocation\ProductsAllocationsGetController
  defaults: { auth: false }
  methods: GET