supermarket:
    resource: supermarket-routes.yaml

user:
    resource: user-routes.yaml

job:
    resource: job-routes.yaml

category:
    resource: category-routes.yaml

tax:
    resource: tax-routes.yaml