supermarket:
    resource: supermarket-routes.yaml

user:
    resource: user-routes.yaml

job:
    resource: job-routes.yaml

category:
    resource: category-routes.yaml

tax:
    resource: tax-routes.yaml

supplier:
    resource: supplier-routes.yaml

product:
    resource: product-routes.yaml

product_allocation:
    resource: product-allocation-routes.yaml