sale_line_put:
  path: /sale_line/{id}
  controller: SuperVMar\App\Controller\Sale\SaleLinePutController
  defaults: { auth: false }
  methods: PUT

sale_get:
  path: /sale/{id}
  controller: SuperVMar\App\Controller\Sale\SaleGetController
  defaults: { auth: false }
  methods: GET

sale_finish_patch:
  path: /sale_finish/{id}
  controller: SuperVMar\App\Controller\Sale\SaleFinishPutController
  defaults: { auth: false }
  methods: PATCH