supermarket_put:
  path: /supermarket/{id}
  controller: SuperVMar\App\Controller\Supermarket\SupermarketPutController
  defaults: { auth: false }
  methods: PUT

supermarket_get:
  path: /supermarket/{id}
  controller: SuperVMar\App\Controller\Supermarket\SupermarketGetController
  defaults: { auth: false }
  methods: GET

zones_get:
  path: /zones/{idSupermarket}
  controller: SuperVMar\App\Controller\Supermarket\ZonesGetController
  defaults: { auth: false }
  methods: GET