supermarket_put:
  path: /supermarket/{id}
  controller: SuperVMar\App\Controller\Supermarket\SupermarketPutController
  methods: PUT

supermarket_get:
  path: /supermarket/{id}
  controller: SuperVMar\App\Controller\Supermarket\SupermarketGetController
  methods: GET

supermarkets_get:
  path: /supermarkets
  controller: SuperVMar\App\Controller\Supermarket\SupermarketsGetController
  methods: GET

zones_get:
  path: /zones/{idSupermarket}
  controller: SuperVMar\App\Controller\Supermarket\ZonesGetController
  methods: GET