services:
  database:
    container_name: ${PROJECT_NAME}_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_USER: fran
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - supervmar

  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: ./
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    volumes:
      - ./api-vmar:/var/www/html/api-vmar
    depends_on:
      - database
      - rabbitmq
    networks:
      - supervmar

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./api-vmar:/var/www/html/api-vmar
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - supervmar

  rabbitmq:
    image: rabbitmq:4-management
    container_name: ${PROJECT_NAME}_rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: /${PROJECT_NAME}
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    volumes:
      - superubemar_queue_system_local:/var/lib/rabbitmq/
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672"
    networks:
      - supervmar

volumes:
  superubemar_queue_system_local:

networks:
  supervmar:
    name: supervmar